name: CI
on:
  push:
    branches:
       - master
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: voronenko/cdci-scanners:latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: semgrep(sarif)
        run: |
          make semgrep-sarif || true

      - name: semgrep(junit)
        run: |
          make semgrep-junit || true

# eslint . --ext .js,.jsx,.ts,.tsx --ignore-pattern *.test.ts  -f @microsoft/eslint-formatter-sarif -o eslint.sarif || true
      - name: eslint
        run: |
          eslint . -f json --ext .js,.jsx,.ts,.tsx --ignore-pattern *.test.ts -o eslint-report.json . || true

      - name: convert junit results to sarif
        run: |
          sarif-junit -i ./semgrep.sarif -o ./semgrep_converted.junit
          ls *.sarif *.junit

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: './*.junit'
